### ISSUE TITLE
Looks like the github api changed?

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#199]
```
warning: There are too many unreachable loose objects; run 'git prune' to remove them.
+ [/opt/miq_bot/repos/ManageIQ/cc_monitor] git rev-parse --git-dir --show-toplevel # => ".git\n/opt/miq_bot/repos/ManageIQ/cc_monitor\n"2016-06-30T21:56:18.423Z 16738 TID-oto7pbhe4 PullRequestMonitor JID-90dce0d3c4a27b3f1a040a10 INFO: fail: 64.01 sec

2016-06-30T21:56:18.423Z 16738 TID-oto7pbhe4 WARN: {"class"=>"PullRequestMonitor", "args"=>[], "retry"=>false, "queue"=>"miq_bot_glacial", "jid"=>"90dce0d3c4a27b3f1a040a10", "created_at"=>1467323432.9528632, "enqueued_at"=>1467323714.412577}
+ git remote2016-06-30T21:56:18.442Z 16738 TID-oto7pbhe4 WARN: NoMethodError: undefined method `html_url' for nil:NilClass

2016-06-30T21:56:18.442Z 16738 TID-oto7pbhe4 WARN: /opt/miq_bot/app/workers/pull_request_monitor/pr_branch_record.rb:5:in `create'
/opt/miq_bot/app/workers/pull_request_monitor/repo_processor.rb:11:in `block (2 levels) in process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/github_api-0.11.3/lib/github_api/response_wrapper.rb:112:in `block in each'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/github_api-0.11.3/lib/github_api/response_wrapper.rb:112:in `each'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/github_api-0.11.3/lib/github_api/response_wrapper.rb:112:in `each'
/opt/miq_bot/app/workers/pull_request_monitor/repo_processor.rb:7:in `block in process'
/opt/miq_bot/app/models/repo.rb:57:in `block in with_github_service'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:17:in `block in call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:27:in `block in synchronize'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:27:in `synchronize'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:27:in `synchronize'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:17:in `call'
/opt/miq_bot/app/models/repo.rb:57:in `with_github_service'
/opt/miq_bot/app/workers/pull_request_monitor/repo_processor.rb:6:in `process'
/opt/miq_bot/app/workers/pull_request_monitor.rb:17:in `block in perform'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/opt/miq_bot/app/workers/pull_request_monitor.rb:13:in `perform'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:18:in `call_with_sidetiq_history'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:6:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by Fryguy** [comment]
Fixed in #208
