### ISSUE TITLE
undefined method `subject' for [:message, "Moved Permanently"]:Array

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#234]
```
==> log/foreman/sidekiq-1.log <==
2016-12-06T18:56:10.438Z 3104 TID-owx7s8pe4 GithubNotificationMonitorWorker JID-65c63f0ff904031f4ead31cc ERROR: undefined method `subject' for [:message, "Moved Permanently"]:Array
2016-12-06T18:56:10.439Z 3104 TID-owx7s8pe4 GithubNotificationMonitorWorker JID-65c63f0ff904031f4ead31cc ERROR: /opt/miq_bot/app/models/git_hub_api/notification.rb:23:in `extract_issue_id'
/opt/miq_bot/app/models/git_hub_api/notification.rb:6:in `initialize'
/opt/miq_bot/app/models/git_hub_api/repo.rb:15:in `new'
/opt/miq_bot/app/models/git_hub_api/repo.rb:15:in `block in notifications'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/resource.rb:125:in `each'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/resource.rb:125:in `each'
/opt/miq_bot/app/models/git_hub_api/repo.rb:14:in `collect'
/opt/miq_bot/app/models/git_hub_api/repo.rb:14:in `notifications'
/opt/miq_bot/app/models/github_notification_monitor.rb:40:in `process_notifications'
/opt/miq_bot/app/workers/github_notification_monitor_worker.rb:27:in `process_notifications'
/opt/miq_bot/app/workers/github_notification_monitor_worker.rb:22:in `block in process_repos'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:46:in `each'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:46:in `each'
/opt/miq_bot/app/workers/github_notification_monitor_worker.rb:21:in `process_repos'
/opt/miq_bot/app/workers/github_notification_monitor_worker.rb:13:in `perform'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:18:in `call_with_sidetiq_history'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:6:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
2016-12-06T18:56:13.019Z 3104 TID-owx7s8pe4 GithubNotificationMonitorWorker JID-65c63f0ff904031f4ead31cc INFO: done: 10.077 sec
```

and...

```
2016-12-13T14:37:24.483Z 3102 TID-ou2mi2gl0 PullRequestMonitor JID-8dcb0e66ef6b3640e69b07e5 INFO: fail: 137.497 sec
2016-12-13T14:37:24.484Z 3102 TID-ou2mi2gl0 WARN: {"class":"PullRequestMonitor","args":[],"retry":false,"queue":"miq_bot_glacial","jid":"8dcb0e66ef6b3640e69b07e5","created_at":1481639400.4528453,"enqueued_at":1481639706.985065}
2016-12-13T14:37:24.484Z 3102 TID-ou2mi2gl0 WARN: NoMethodError: undefined method `number' for ["message", "Moved Permanently"]:Array
2016-12-13T14:37:24.484Z 3102 TID-ou2mi2gl0 WARN: /opt/miq_bot/app/workers/pull_request_monitor.rb:33:in `block (2 levels) in github_prs'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/github_api-0.11.3/lib/github_api/response_wrapper.rb:112:in `block in each'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/github_api-0.11.3/lib/github_api/response_wrapper.rb:112:in `each'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/github_api-0.11.3/lib/github_api/response_wrapper.rb:112:in `each'
/opt/miq_bot/app/workers/pull_request_monitor.rb:31:in `collect'
/opt/miq_bot/app/workers/pull_request_monitor.rb:31:in `block in github_prs'
/opt/miq_bot/app/models/repo.rb:63:in `block in with_github_service'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:17:in `block in call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:27:in `block in synchronize'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:27:in `synchronize'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:27:in `synchronize'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/bundler/gems/miq_tools_services-f0439d49e117/lib/miq_tools_services/service_mixin.rb:17:in `call'
/opt/miq_bot/app/models/repo.rb:63:in `with_github_service'
/opt/miq_bot/app/workers/pull_request_monitor.rb:30:in `github_prs'
/opt/miq_bot/app/workers/pull_request_monitor.rb:24:in `process_repo'
/opt/miq_bot/app/workers/pull_request_monitor.rb:18:in `block in process_repos'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:46:in `each'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/activerecord-4.2.7/lib/active_record/relation/delegation.rb:46:in `each'
/opt/miq_bot/app/workers/pull_request_monitor.rb:18:in `process_repos'
/opt/miq_bot/app/workers/pull_request_monitor.rb:13:in `perform'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:152:in `execute_job'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:18:in `call_with_sidetiq_history'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:6:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/logging.rb:32:in `with_context'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `call'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:129:in `block in process'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:168:in `stats'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:128:in `process'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:80:in `process_one'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/processor.rb:68:in `run'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:17:in `watchdog'
/opt/rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/gems/sidekiq-4.1.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by NickLaMuro** [comment]
@bdunne @Fryguy So I was testing out things myself here:

https://github.com/GrumpyTech/miqbot-sandbox/pull/1

And the bot was adding labels just fine.  But one thing I did to start was just create the repo above at `NickLaMuro/miqbot-sandbox`, then moved it to my "GrumpyTech" org (since I had to tweak [this line](https://github.com/ManageIQ/miq_bot/blob/master/app/models/git_hub_api/user.rb#L6) to use `:user` instead when I was just using my base account), I forgot to update the `config/settings/development.local.yml` to include the updated `org/repo` change from `NickLaMuro/miqbot-sandbox` => `GrumpyTech/miqbot-sandbox`.

This didn't cause errors for me, but the bot just didn't do anything for a while, and it makes me wonder if the errors above weren't caused by a repo transfer, and either:

a) There are some stale notifications causing the issues shown above (hence the "Moved Permanently
b) Stale config settings that are doing something similar as well

I think the original thought was that the API endpoint changed, but maybe in this case it is actually a redirect with the API for a moved repo instead.

Not sure the best way to handle it since I can't recreate, but and idea I have for this in the future might be to put a rescue around the `.process_notification`, log the error, but move on to the other notifications so the bot doesn't lock up from this on a particular repo (which it looks like it is doing in this case).  Since I can't confirm one the the above issues is causing the problem, I am not going to try and implement a solution for it at this time, but at least putting the suggestion out there to start the discussion on it... also... it is late... 😴

**Comment by Fryguy** [comment]
@NickLaMuro Did you also change the "name" column for the repo to `GrumpyTech/miqbot-sandbox` ?

**Comment by NickLaMuro** [comment]
@Fryguy yeah, when I switched the repo, I just completely deleted the existing DB and re-went through the last couple steps in the `README`, updating the repo name where appropriate.  My mistake that I described above is that I didn't update the settings when doing that.

**Comment by Fryguy** [comment]
Ok, I think I got this figured out.  We had renamed (a long time ago) ManageIQ/ansible_tower_client to ansible/ansible_tower_client_ruby and for some reason it just started giving problems now.  GitHub must mark renames as a temporary rename for a short time, but then after more time they just convert it to a "Moved Permanently".
