### ISSUE TITLE
Yamllint tests fail if yamllint isn't installed

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/miq_bot#379]
```
    Failure/Error: _out, err, _ps = Open3.capture3("yamllint -v")
     
     Errno::ENOENT:
       No such file or directory - yamllint
     # ./app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb:129:in `yamllint_version'
     # ./app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb:45:in `header'
     # ./app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb:59:in `build_comments'
     # ./app/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder.rb:13:in `comments'
     # ./spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ./spec/workers/commit_monitor_handlers/commit_range/rubocop_checker/message_builder_spec.rb:21:in `block (3 levels) in <top (required)>'
```

- We probably shouldn't be shelling out to yamllint during tests
- We should probably handle missing linters better (don't blow up, maybe just skip the linting)

**Comment by bdunne** [comment]
Copying in comment from @Fryguy in #392 since these are essentially the same issue...

> There are a few approaches to fixing this...not sure what's best
> 
>     * When the yamllint files don't exist, use a shared file from guides
> 
>     * When the yamllint files don't exist, assuming linting is disabled and don't lint at all
> 
>     * Add enable/disable support for individual linters, then fail or fallback when the files don't exist
> 
>     * Send an email instead of making a comment
> 
> 
> Also, should the same rules apply for haml lint and rubocop as well?
